name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag name"
        required: true
        default: 'v1'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Build docker image and push to dockerhub

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check out the libretranslate repo
        run: |
          set -ex
          cp start.sh LibreTranslate/start.sh
          echo "COPY --chmod=775 start.sh /start.sh" | tee -a LibreTranslate/docker/Dockerfile
          echo 'ENTRYPOINT ["/start.sh"]' | tee -a LibreTranslate/docker/Dockerfile
          cat LibreTranslate/docker/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: 'LibreTranslate'
          no-cache: true
          file: 'LibreTranslate/docker/Dockerfile'
          tags: ghcr.io/szaimen/aio-libretranslate:${{ github.event.inputs.tagName }}
          provenance: false
