name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag name"
        required: true
        default: 'v1'
        
jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Build docker image and push to dockerhub

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check out the libretranslate repo
        run: |
          set -ex
          mkdir -p libretranslate
          git clone https://github.com/LibreTranslate/LibreTranslate.git --branch v1.3.13 --depth 1 libretranslate
          cp ./start.sh ./libretranslate/
          echo "COPY --chmod=775 start.sh /start.sh" >> ./libretranslate/docker/Dockerfile
          echo "ENTRYPOINT ['/start.sh']" >> ./libretranslate/docker/Dockerfile
          cat ./libretranslate/docker/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: './libretranslate/'
          no-cache: true
          file: './libretranslate/docker/Dockerfile'
          tags: szaimen/aio-libretranslate:${{ github.event.inputs.tagName }}
          provenance: false
