name: update submodules

on:
  workflow_dispatch:
  schedule:
  - cron:  '00 12 * * *'

jobs:
  submodules:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.update.outputs.version }}
    name: update submodules
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: update libreoffice
      id: update
      run: |
         libre_version="$(
          git ls-remote https://github.com/LibreTranslate/LibreTranslate v* \
            | cut -d/ -f3 \
            | sort -V \
            | grep -E "^v[0-9\.]+$" \
            | tail -1
         )"
         cd LibreTranslate
         git fetch --unshallow
         git checkout $libre_version
         echo "version=$libre_version" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: submodules automated change
        signoff: true
        title: submodules update to "${{needs.submodules.outputs.output1}}"
        body: Automated submodules update
        branch: submodules-update
